#!/bin/sh

URL=https://svn.omniti.com/people/wez/php/lemon
wd=/tmp/dist.$$

old=`pwd`

mkdir $wd
cd $wd || exit 1

v=`svn info $URL | awk '/^Revision:/ { print $2 }'`

svn export $URL lemon-php-$v
tar cvzf lemon-php-$v.tgz lemon-php-$v

cp lemon-php-$v.tgz $old
cd $old
rm -rf $wd

